"""
Django settings for my_env project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from django.core.mail import send_mail
#to access environment variables
import os 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FEEDLY_ACCESS_TOKEN = "A0KyS6MsNEofNneE4wccVDuje1549tJzm78VzNlJ9cCWupmqv8mKtKkhuChQi6Fw1oJplc2nhFEbxpYIDUoefELnYN6WFOKzxo0GJ454kXOh1x6agEEM26crJYhiK2LazrsZw04AE7hS25cS-GDYO5md2_u09UTeM9shGVB_f9SJMDxZu2LOEpZ1TWgPbbLGApSJdA1fK9vBLNZgNqAVXv1GpqC48FAAAMYi9-V4j2w8F3-HFwR6ofw8_fY:feedlydev"



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-1h&ziw^-$9*^&!1lh-5@oi^d+^3p5dvtr)texgb=8dzd$(2_kw"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main", 
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "my_env.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'main', 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "my_env.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR + "db.sqlite3",
    }}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

#added by me
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]
STATIC_URL = '/static/'
#added by me
STATIC_ROOT = os.path.join(BASE_DIR, "static_cdn")
#here we add the API key
API_KEY = ""

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'main', 'static')]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'email-smtp.eu_north-1'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'AKIA32QTBVBS7CN3HMC4'
EMAIL_HOST_PASSWORD = 'BLQfnVaq6DcpYaXoC6z3Dqny6jffqjwmSCx+aU2ZbJbG'
DEFAULT_FROM_EMAIL = 'florin.negrea@arobs.com'
AWS_REGION = 'eu-north-1'
AWS_ACCESS_KEY = 'AKIA32QTBVBS7C3PHCV3'
AWS_SECRET_KEY = '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'


EMAIL_HOST_SMTP = 'smtp.office365.com'
EMAIL_HOST_USER_SMTP = 'florin.negrea@arobs.com'
EMAIL_HOST_PASSWORD = 'Oem23Rvp@22'


