# Generated by Django 2.1.15 on 2023-06-11 12:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230611_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
