# Generated by Django 2.1.15 on 2023-06-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230611_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='unique_id',
        ),
    ]
